=== MikelSalazar/CoEditAR/documentation/schema/sources/root.schema.json
{
	"$id": "https://coeditar.com/schema/files/root.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Root",
	"description": "The root of the CoEditAR document.",
	"$comment": "root",
	"properties": {
		"CoEditAR": { 
			"title": "CoEditAR",
			"description": "The version number of the CoEditAR document.",
			"type": "number",
			"default": 0.1,
			"minimum": 0
		},
		"models": {
			"title": "Models",
			"description": "The semantic models of the CoEditAR document.",
			"type": "array",
			"items": { "$ref": "model/model.schema.json" }
		},
		"spaces": {
			"title": "Spaces",
			"description": "The interaction spaces.",
			"type": "array",
			"items": { "$ref": "space/space.schema.json" }
		},
		"experiences": {
			"title": "Experiences",
			"description": "The user experiences.",
			"type": "array",
			"items": { "$ref": "experience/experience.schema.json" }
		},
		"users": {
			"title": "Users",
			"description": "The users of an interaction space.",
			"type": "array",
			"items": { "$ref": "user/user.schema.json" }
		}
	},
	"required": ["CoEditAR"]
}

=== MikelSalazar/CoEditAR/documentation/schema/tests/coeditar.schema.test.json
{
	"$schema": "../builds/coeditar.schema.json",
	"CoEditAR": 0.1,
	"models": [
		{
			"name": "model01",
			"classes": [
				{
					"name": "class01",
					"properties": [
						{ "name": "property01", "type": "boolean" },
						{ "name": "property02", "type": "number" },
						{ "name": "property03", "type": "string" }
					]
				}
			]
		}
	],
	"spaces": [ 
		{
			"name": "space01",
			"spaces": [ { "name": "sub-space01"} ],
			"entities": [ 
				{
					"name": "entity01",
					"entities": [ { "name": "sub-entity01" }]
				}
			]
		}
	],
	"users": [
		{ 
			"name": "user01"
		}
	],
	"experiences": [
		{
			"name": "experience01",
			"widgets": [
				{
					"name": "widget01",
					"widgets": [ { "name": "sub-widget01" } ]
				}
			]
		}
	]
}
